version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

